### PR TITLE
feat: add promise mode and other functions.

### PR DESCRIPTION
**Pull request by AntiMoron**
```javascript
// option's been extended.
opts: {
  sync: true, // for sync usage.
  promise: true, // if set, return a promise object.
  args: ['-b', 'tags/0.0.1'], // for user defined arguments.
  progress: true, // if set, add '--progress' flag.
}
```
event listener's been added.

```
/**
 *
 * @param {string} repo repo's clone path
 * @param {string} targetPath save path
 * @param {Object} opts options
 * @param {function} cb callback function
 * @param {function} el event listener, $0 process, $1 event, $2 & $3 callback params.
 * @return {promise}
 */
module.exports = function (repo, targetPath, opts, cb, el)
```

### CODE REVIEW

**Comment by MichaelDimmitt** [comment]
+1

**Comment by alexandrtovmach** [comment]
@jaz303 Could you take a look?

**Comment by jaz303** [comment]
I think the time has come to use `Promise` by default, and bump the major version. Any objections?

**Comment by alexandrtovmach** [comment]
@jaz303 For sure, better to keep backward compatible version, so my suggestion is to have two methods:
- `cloneSync` - sync
- `clone` - async

**Comment by 4086606** [comment]
When can the two methods be implemented in the NPM module?

**Comment by ReshmiCode** [comment]
Is this or the other PR that solves https://github.com/jaz303/git-clone/issues/6 going to be merged and added soon?

**Comment by jaz303** [comment]
hi folks i've had a turbulent 18 months (as i'm sure most of have too). looking at this now.

**Pull request closed without merging**
